### ISSUE TITLE
[BUG/ERROR]

### ISSUE THREAD

**Issue by Eliheakins** [forrestdavis/NLPScholar#14]
## Describe the bug

NLPscholar is expecting a lemma col for a MinimalPair exp

## To Reproduce

Run main.py with provided config file

## Expected behavior

To run exp

## Observed behavior 

Reading from config.yaml
Loading data from Hw2/aclImdb/test/PositiveTestSentid.txt...
Traceback (most recent call last):
  File "/home/eheakins/NLPScholar/main.py", line 27, in <module>
    exp.evaluate()
  File "/home/eheakins/NLPScholar/src/evaluations/MinimalPair.py", line 109, in evaluate
    self.columnCheck()
  File "/home/eheakins/NLPScholar/src/evaluations/Evaluation.py", line 47, in columnCheck
    assert need in columns, f"Missing {need} in {self.datafpath}"
AssertionError: Missing lemma in Hw2/aclImdb/test/PositiveTestSentid.txt

## Additional context

Link to necessary files https://drive.google.com/drive/folders/1aUZxTzZMsyL44zdBBl33B-5aTexiyWVv?usp=drive_link

**Comment by forrestdavis** [comment]
`checkColumns` should be `checkFileColumns`
